version: "3"

services:
  # ScyllaDB Nodes
  scylla_node1:
    image: scylladb/scylla:latest
    container_name: scylla_node1
    environment:
      - SCYLLA_SEEDS=scylla_node1
    volumes:
      - node1_data:/var/lib/scylla

  scylla_node2:
    image: scylladb/scylla:latest
    container_name: scylla_node2
    environment:
      - SCYLLA_SEEDS=scylla_node1
    volumes:
      - node2_data:/var/lib/scylla

  scylla_node3:
    image: scylladb/scylla:latest
    container_name: scylla_node3
    environment:
      - SCYLLA_SEEDS=scylla_node1
    volumes:
      - node3_data:/var/lib/scylla

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:v2.31.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Grafana for visualization
  grafana:
    image: grafana/grafana:8.3.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    ports:
      - "9100:9100"

  scylla-manager:
    image: scylladb/scylla-manager:latest
    ports:
      - "5090:5090"
networks:
  scylla-network:
    name: scylla-network

# Define volumes
volumes:
  node1_data:
  node2_data:
  node3_data:
  grafana_data:
