//! Shared types for grammar practice, placement and the brainmap.
//!
//! A grammar item crosses the wire without its answer. The server regrades
//! every submission against the stored revision, so sending the answer to the
//! client would buy nothing and give it away; the client shows a verdict the
//! server returned.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// What a learner is asked, stripped of anything that would answer it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GrammarItemDto {
    pub item_id: i32,
    pub revision: i32,
    pub rule_id: i32,
    pub rule_slug: String,
    pub rule_title: String,
    pub rule_explanation: String,
    pub level: String,
    pub prompt: String,
    pub hint: Option<String>,
    /// The options of a multiple choice, by stable identifier. Empty for a
    /// cloze, which the learner types.
    pub options: Vec<GrammarOptionDto>,
}

/// One choice, identified by something that survives being shuffled.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GrammarOptionDto {
    pub id: String,
    pub text: String,
}

/// An open session and the items it served.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GrammarSessionDto {
    pub session_id: Uuid,
    pub items: Vec<GrammarItemDto>,
}

/// One answer, as a client reports it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SubmissionDto {
    pub session_id: Uuid,
    /// Generated by the client so that a resent answer is recorded once.
    pub event_id: Uuid,
    pub item_id: i32,
    pub revision: i32,
    /// Typed text for a cloze, or an option identifier for a multiple choice.
    pub answer: String,
    pub chose_option: bool,
    pub hint_shown: bool,
    pub ordinal: u32,
    /// When the learner answered, which is not when the server heard about it.
    pub occurred_at: DateTime<Utc>,
}

/// The server's ruling, which is the only one that counts.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VerdictDto {
    pub event_id: Uuid,
    pub correct: bool,
}

/// How confidently a point is known, as the brainmap paints it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MasteryBandDto {
    Unseen,
    Red,
    Amber,
    Green,
    ProvisionalRed,
    ProvisionalAmber,
    ProvisionalGreen,
}

/// One cell of the brainmap.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BrainmapCellDto {
    pub rule_id: i32,
    pub slug: String,
    pub title: String,
    pub level: String,
    pub band: MasteryBandDto,
    /// `None` where the point has never been attempted.
    ///
    /// Single precision, as the card snapshot's figures are: this colours a
    /// cell and prints a percentage, while the authoritative double lives in
    /// `grammar_mastery`. It also survives the wire intact, which a double
    /// does not — `serde_json` parses without its `float_roundtrip` feature
    /// and can return a double one unit in the last place adrift.
    pub accuracy: Option<f32>,
    pub attempts: i32,
    /// `reference` where a curated inventory supplied the point, `llm`
    /// otherwise. A learner may reasonably trust the two differently.
    pub provenance: String,
}

/// The whole map for one language, in syllabus order.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BrainmapDto {
    pub language: String,
    pub cells: Vec<BrainmapCellDto>,
}

/// Where a placement run stands: another level, or a verdict.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum PlacementStateDto {
    Testing(PlacementStepDto),
    Finished(PlacementResultDto),
}

/// One level of a placement run put to the learner.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlacementStepDto {
    pub attempt_id: Uuid,
    pub session_id: Uuid,
    pub level: String,
    pub items: Vec<GrammarItemDto>,
}

/// How one level of a placement run scored.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlacementLevelDto {
    pub level: String,
    pub correct: i64,
    pub asked: i64,
    pub passed: bool,
}

/// The verdict of a finished placement run.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlacementResultDto {
    pub attempt_id: Uuid,
    /// The highest level passed; `None` where even the first was not.
    pub level_reached: Option<String>,
    pub tested: Vec<PlacementLevelDto>,
    /// Levels whose bank was too thin to judge. Untested is not failed.
    pub skipped: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;
    use serde::{de::DeserializeOwned, Serialize};
    use std::fmt::Debug;

    fn assert_json_roundtrip<T>(value: &T)
    where
        T: Serialize + DeserializeOwned + PartialEq + Debug,
    {
        let json = serde_json::to_vec(value).expect("serialize");
        let decoded: T = serde_json::from_slice(&json).expect("deserialize");
        assert_eq!(&decoded, value);
    }

    fn item(item_id: i32) -> GrammarItemDto {
        GrammarItemDto {
            item_id,
            revision: 1,
            rule_id: 4,
            rule_slug: "ser-vs-estar".into(),
            rule_title: "Ser vs estar".into(),
            rule_explanation: "Permanent against temporary.".into(),
            level: "A1".into(),
            prompt: "Yo ___ cansado.".into(),
            hint: Some("A passing state.".into()),
            options: vec![GrammarOptionDto {
                id: "o1".into(),
                text: "estoy".into(),
            }],
        }
    }

    #[test]
    fn a_served_item_never_carries_its_answer() {
        let json = serde_json::to_string(&item(1)).expect("serialize");
        assert!(!json.contains("\"answer\""));
        assert!(!json.contains("correct_option"));
    }

    proptest! {
        #[test]
        fn session_and_submission_json_roundtrip(
            item_id in 1i32..i32::MAX,
            ordinal in 1u32..20,
            timestamp in 1_600_000_000i64..2_000_000_000,
        ) {
            let occurred_at = DateTime::from_timestamp(timestamp, 0).expect("timestamp");
            let session_id = Uuid::from_u128(u128::from(ordinal));

            assert_json_roundtrip(&GrammarSessionDto {
                session_id,
                items: vec![item(item_id)],
            });
            assert_json_roundtrip(&SubmissionDto {
                session_id,
                event_id: Uuid::from_u128(u128::from(ordinal).saturating_add(1)),
                item_id,
                revision: 1,
                answer: "estoy".into(),
                chose_option: false,
                hint_shown: true,
                ordinal,
                occurred_at,
            });
            assert_json_roundtrip(&VerdictDto {
                event_id: Uuid::from_u128(u128::from(ordinal)),
                correct: true,
            });
        }

        #[test]
        fn brainmap_and_placement_json_roundtrip(
            accuracy in 0.0f32..=1.0,
            asked in 1i64..10,
        ) {
            assert_json_roundtrip(&BrainmapDto {
                language: "es".into(),
                cells: vec![
                    BrainmapCellDto {
                        rule_id: 4,
                        slug: "ser-vs-estar".into(),
                        title: "Ser vs estar".into(),
                        level: "A1".into(),
                        band: MasteryBandDto::Amber,
                        accuracy: Some(accuracy),
                        attempts: 3,
                        provenance: "reference".into(),
                    },
                    BrainmapCellDto {
                        rule_id: 5,
                        slug: "gender-agreement".into(),
                        title: "Gender agreement".into(),
                        level: "A1".into(),
                        band: MasteryBandDto::Unseen,
                        accuracy: None,
                        attempts: 0,
                        provenance: "llm".into(),
                    },
                ],
            });

            assert_json_roundtrip(&PlacementStateDto::Finished(PlacementResultDto {
                attempt_id: Uuid::from_u128(7),
                level_reached: Some("A2".into()),
                tested: vec![PlacementLevelDto {
                    level: "A1".into(),
                    correct: asked,
                    asked,
                    passed: true,
                }],
                skipped: vec!["B1".into()],
            }));

            assert_json_roundtrip(&PlacementStateDto::Testing(PlacementStepDto {
                attempt_id: Uuid::from_u128(7),
                session_id: Uuid::from_u128(8),
                level: "A2".into(),
                items: vec![item(1)],
            }));
        }
    }
}

/// Whether a feed row wrote something or removed it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GrammarChangeOperationDto {
    Upsert,
    Delete,
}

/// A grammar item as a device holds it offline.
///
/// This one carries the answer, which the served [`GrammarItemDto`] withholds.
/// A device that cannot reach the server still has to tell the learner whether
/// they were right, so the bank it caches must contain the answer; the verdict
/// it shows is provisional, and the server regrades every attempt on upload.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OfflineGrammarItemDto {
    pub item_id: i32,
    pub revision: i32,
    pub rule_id: i32,
    pub rule_slug: String,
    pub rule_title: String,
    pub rule_explanation: String,
    pub level: String,
    pub language: String,
    pub prompt: String,
    pub hint: Option<String>,
    pub options: Vec<GrammarOptionDto>,
    /// The expected text of a cloze; `None` for a multiple choice.
    pub answer: Option<String>,
    /// Further texts a cloze accepts, such as a contracted form.
    pub accepted: Vec<String>,
    /// Which option identifier is correct; `None` for a cloze.
    pub correct_option: Option<String>,
}

/// One item entering, changing in, or leaving the bank.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GrammarBankChangeDto {
    pub sequence: i64,
    pub item_id: i32,
    pub operation: GrammarChangeOperationDto,
    /// The item itself, for a change a device should hold. It is absent for a
    /// deletion, and also for an item that has left `active` status: either
    /// way the device drops it.
    pub item: Option<OfflineGrammarItemDto>,
}

/// Asks for the next page of bank changes for one language.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GrammarBankChangeRequestDto {
    pub protocol_version: u16,
    pub language: String,
    pub cursor: i64,
    pub limit: u16,
}

/// A page of bank changes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GrammarBankChangePageDto {
    pub protocol_version: u16,
    pub language: String,
    pub changes: Vec<GrammarBankChangeDto>,
    pub next_cursor: i64,
    pub has_more: bool,
}

/// One learner's projection for one grammar point, as a device mirrors it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GrammarMasteryStateDto {
    pub rule_id: i32,
    pub rule_slug: String,
    pub stability: f32,
    pub difficulty: f32,
    pub elapsed_days: i32,
    pub scheduled_days: i32,
    pub reps: i32,
    pub lapses: i32,
    pub state: i16,
    /// `None` where the point has never been attempted. Single precision, for
    /// the reason [`BrainmapCellDto::accuracy`] gives.
    pub accuracy: Option<f32>,
    pub attempts: i32,
    pub last_review: Option<DateTime<Utc>>,
    pub due: DateTime<Utc>,
}

/// One mastery row moving.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GrammarMasteryChangeDto {
    pub sequence: i64,
    pub rule_id: i32,
    pub operation: GrammarChangeOperationDto,
    /// Absent for a deletion.
    pub mastery: Option<GrammarMasteryStateDto>,
}

/// Asks for the next page of mastery changes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GrammarMasteryChangeRequestDto {
    pub protocol_version: u16,
    pub cursor: i64,
    pub limit: u16,
}

/// A page of mastery changes.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GrammarMasteryChangePageDto {
    pub protocol_version: u16,
    pub changes: Vec<GrammarMasteryChangeDto>,
    pub next_cursor: i64,
    pub has_more: bool,
}

/// One answer a device recorded while it could not reach the server.
///
/// It names its own session, which the server may never have seen, so the
/// language and level it ran at travel with it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OfflineAttemptDto {
    pub session_id: Uuid,
    pub event_id: Uuid,
    pub item_id: i32,
    pub revision: i32,
    pub answer: String,
    pub chose_option: bool,
    pub hint_shown: bool,
    pub ordinal: u32,
    pub occurred_at: DateTime<Utc>,
    pub language: String,
    pub level: Option<String>,
}

/// A batch of offline answers.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GrammarAttemptBatchRequestDto {
    pub protocol_version: u16,
    pub device_id: Uuid,
    pub attempts: Vec<OfflineAttemptDto>,
}

/// What became of one uploaded answer.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum OfflineAttemptStatusDto {
    /// Recorded, with the server's own verdict.
    Accepted(VerdictDto),
    /// Already held, so nothing was written. The verdict is the stored one, so
    /// a device that never received the first acknowledgement still converges.
    Duplicate(VerdictDto),
    /// Refused, with a reason a device can log but not act on.
    Rejected { event_id: Uuid, reason: String },
}

/// The outcome of a batch.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GrammarAttemptBatchResponseDto {
    pub protocol_version: u16,
    pub results: Vec<OfflineAttemptStatusDto>,
}
