//! Grammar attempts and the mastery projections they produce.
//!
//! Persistence here is deliberately thin. Attempts are appended and never
//! amended; both mastery numbers are recomputed from a baseline plus the whole
//! attempt stream by the pure code in `wisecrow-learning`. Nothing in the
//! database decides anything, which is what allows an attempt uploaded late by
//! a device that has been offline — even one older than attempts already
//! processed — to re-form its interaction and yield the result it would have
//! had it never been delayed.

use chrono::{DateTime, Utc};
use sqlx::{PgPool, Postgres, Transaction};
use uuid::Uuid;
use wisecrow_learning::mastery::{project, Attempt, Projection};
use wisecrow_learning::srs::{CardState, CardStatus as LearningCardStatus};

use crate::errors::WisecrowError;
use crate::srs::scheduler::CardStatus;

/// Where an attempt was made.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AttemptSource {
    Web,
    Mobile,
}

impl AttemptSource {
    const fn as_str(self) -> &'static str {
        match self {
            Self::Web => "web",
            Self::Mobile => "mobile",
        }
    }
}

/// One submission, as it is written to the stream.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AttemptRecord {
    /// Generated by the client, so that a resent upload is recorded once.
    pub event_id: Uuid,
    pub session_id: Uuid,
    pub device_id: Option<Uuid>,
    pub rule_id: i32,
    pub item_id: i32,
    /// The revision the learner actually saw, so that regrading stays honest.
    pub item_revision: i32,
    /// Position within the interaction, counting from one.
    pub ordinal: i16,
    pub correct: bool,
    pub hint_shown: bool,
    pub occurred_at: DateTime<Utc>,
    pub source: AttemptSource,
}

/// One grammar point with whatever mastery the learner has on it.
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct MasteryRow {
    pub rule_id: i32,
    pub slug: String,
    pub title: String,
    pub level: String,
    /// Provenance tier of the point itself: `llm` or `reference`.
    pub source: String,
    /// `None` where the point has never been attempted, which is what keeps it
    /// grey rather than colouring it as failure.
    pub accuracy: Option<f64>,
    pub attempts: i32,
    pub reps: i32,
    pub state: i16,
    pub due: Option<DateTime<Utc>>,
}

const MASTERY_COLUMNS: &str = "gr.id AS rule_id, gr.slug, gr.title, cl.code AS level,
     gr.source, gm.accuracy, COALESCE(gm.attempts, 0) AS attempts,
     COALESCE(gm.reps, 0) AS reps, COALESCE(gm.state, 0::SMALLINT) AS state, gm.due";

/// Reads and rebuilds grammar mastery.
pub struct MasteryRepository;

impl MasteryRepository {
    /// Appends one attempt and rebuilds the point's projections.
    ///
    /// Both happen in one transaction, so a reader never sees an attempt that
    /// the projections have not yet accounted for.
    ///
    /// # Errors
    ///
    /// Returns an error when a write fails or the stream cannot be replayed.
    pub async fn record_attempt(
        pool: &PgPool,
        user_id: i32,
        record: &AttemptRecord,
    ) -> Result<(), WisecrowError> {
        let mut transaction = pool.begin().await?;
        Self::record_attempt_in_transaction(&mut transaction, user_id, record).await?;
        transaction.commit().await?;
        Ok(())
    }

    pub(crate) async fn record_attempt_in_transaction(
        transaction: &mut Transaction<'_, Postgres>,
        user_id: i32,
        record: &AttemptRecord,
    ) -> Result<(), WisecrowError> {
        ensure_baseline(transaction, user_id, record.rule_id, record.occurred_at).await?;
        insert_attempt(transaction, user_id, record).await?;
        refresh_in_transaction(transaction, user_id, record.rule_id).await
    }

    /// Rebuilds one point's projections from its stored attempts.
    ///
    /// # Errors
    ///
    /// Returns an error when a write fails or the stream cannot be replayed.
    pub async fn refresh_projection(
        pool: &PgPool,
        user_id: i32,
        rule_id: i32,
    ) -> Result<(), WisecrowError> {
        let mut transaction = pool.begin().await?;
        refresh_in_transaction(&mut transaction, user_id, rule_id).await?;
        transaction.commit().await?;
        Ok(())
    }

    /// Recomputes both projections without writing them.
    ///
    /// A point with no baseline has never been attempted and so has nothing to
    /// replay.
    ///
    /// # Errors
    ///
    /// Returns an error when the stream cannot be read or replayed.
    pub async fn replay_from_baseline(
        pool: &PgPool,
        user_id: i32,
        rule_id: i32,
    ) -> Result<Option<Projection>, WisecrowError> {
        let mut transaction = pool.begin().await?;
        let projection = replay(&mut transaction, user_id, rule_id).await?;
        transaction.commit().await?;
        Ok(projection.map(|(projection, _)| projection))
    }

    /// Every syllabus point of a language with the learner's mastery of it.
    ///
    /// Points never attempted are included, because the brainmap must show
    /// what remains as well as what is known.
    ///
    /// # Errors
    ///
    /// Returns an error when the query fails.
    pub async fn mastery_for_language(
        pool: &PgPool,
        user_id: i32,
        lang_code: &str,
    ) -> Result<Vec<MasteryRow>, WisecrowError> {
        let rows = sqlx::query_as::<_, MasteryRow>(&format!(
            "SELECT {MASTERY_COLUMNS}
             FROM grammar_rules gr
             JOIN languages l ON l.id = gr.language_id
             JOIN cefr_levels cl ON cl.id = gr.cefr_level_id
             LEFT JOIN grammar_mastery gm
                 ON gm.rule_id = gr.id AND gm.user_id = $1
             WHERE l.code = $2
             ORDER BY cl.sort_order, gr.slug"
        ))
        .bind(user_id)
        .bind(lang_code)
        .fetch_all(pool)
        .await?;
        Ok(rows)
    }
}

/// Fixes where replay starts for a point, and keeps it ahead of every attempt.
///
/// The baseline is the zero state of a point never scheduled, so its timestamp
/// carries no information beyond "before everything". An attempt arriving out
/// of order with an earlier timestamp therefore simply moves it back; were the
/// baseline ever to be compacted forward over folded-in attempts, this would
/// have to change.
async fn ensure_baseline(
    transaction: &mut Transaction<'_, Postgres>,
    user_id: i32,
    rule_id: i32,
    occurred_at: DateTime<Utc>,
) -> Result<(), WisecrowError> {
    sqlx::query(
        "INSERT INTO grammar_review_baselines (
             user_id, rule_id, stability, difficulty, elapsed_days, scheduled_days,
             reps, lapses, state, last_review, due, captured_at
         ) VALUES ($1, $2, 0.0, 0.0, 0, 0, 0, 0, 0, NULL, $3, $3)
         ON CONFLICT (user_id, rule_id) DO UPDATE
         SET captured_at = LEAST(grammar_review_baselines.captured_at, EXCLUDED.captured_at),
             due = LEAST(grammar_review_baselines.due, EXCLUDED.due)",
    )
    .bind(user_id)
    .bind(rule_id)
    .bind(occurred_at)
    .execute(&mut **transaction)
    .await?;
    Ok(())
}

async fn insert_attempt(
    transaction: &mut Transaction<'_, Postgres>,
    user_id: i32,
    record: &AttemptRecord,
) -> Result<(), WisecrowError> {
    sqlx::query(
        "INSERT INTO grammar_attempts (
             user_id, event_id, session_id, device_id, rule_id, item_id, item_revision,
             ordinal, correct, hint_shown, occurred_at, source
         ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
         ON CONFLICT (user_id, event_id) DO NOTHING",
    )
    .bind(user_id)
    .bind(record.event_id)
    .bind(record.session_id)
    .bind(record.device_id)
    .bind(record.rule_id)
    .bind(record.item_id)
    .bind(record.item_revision)
    .bind(record.ordinal)
    .bind(record.correct)
    .bind(record.hint_shown)
    .bind(record.occurred_at)
    .bind(record.source.as_str())
    .execute(&mut **transaction)
    .await?;
    Ok(())
}

async fn refresh_in_transaction(
    transaction: &mut Transaction<'_, Postgres>,
    user_id: i32,
    rule_id: i32,
) -> Result<(), WisecrowError> {
    let Some((projection, attempts)) = replay(transaction, user_id, rule_id).await? else {
        return Ok(());
    };
    persist_projection(transaction, user_id, rule_id, &projection, attempts).await
}

/// Rebuilds both projections, reporting how many attempts fed them.
async fn replay(
    transaction: &mut Transaction<'_, Postgres>,
    user_id: i32,
    rule_id: i32,
) -> Result<Option<(Projection, i32)>, WisecrowError> {
    let Some(baseline) = load_baseline(transaction, user_id, rule_id).await? else {
        return Ok(None);
    };
    let attempts = load_attempts(transaction, user_id, rule_id, baseline.baseline_at).await?;
    let projection = project(&baseline, &attempts)
        .map_err(|error| WisecrowError::InvalidInput(error.to_string()))?;
    let counted = i32::try_from(attempts.len()).unwrap_or(i32::MAX);
    Ok(Some((projection, counted)))
}

/// The stored baseline, before it is given the shape the scheduler wants.
#[derive(sqlx::FromRow)]
struct BaselineRow {
    stability: f64,
    difficulty: f64,
    elapsed_days: i32,
    scheduled_days: i32,
    reps: i32,
    lapses: i32,
    state: i16,
    last_review: Option<DateTime<Utc>>,
    due: DateTime<Utc>,
    captured_at: DateTime<Utc>,
}

impl BaselineRow {
    fn into_card(self, rule_id: i32) -> CardState {
        CardState {
            // The scheduler is shared with vocabulary, where this field names a
            // translation; for grammar it carries the rule.
            translation_id: rule_id,
            baseline_at: self.captured_at,
            stability: self.stability,
            difficulty: self.difficulty,
            elapsed_days: i64::from(self.elapsed_days),
            scheduled_days: i64::from(self.scheduled_days),
            reps: self.reps,
            lapses: self.lapses,
            status: LearningCardStatus::from(CardStatus::from_db(self.state)),
            last_review: self.last_review,
            due: self.due,
        }
    }
}

async fn load_baseline(
    transaction: &mut Transaction<'_, Postgres>,
    user_id: i32,
    rule_id: i32,
) -> Result<Option<CardState>, WisecrowError> {
    let row = sqlx::query_as::<_, BaselineRow>(
        "SELECT stability, difficulty, elapsed_days, scheduled_days, reps, lapses,
                state, last_review, due, captured_at
         FROM grammar_review_baselines
         WHERE user_id = $1 AND rule_id = $2",
    )
    .bind(user_id)
    .bind(rule_id)
    .fetch_optional(&mut **transaction)
    .await?;

    Ok(row.map(|row| row.into_card(rule_id)))
}

async fn load_attempts(
    transaction: &mut Transaction<'_, Postgres>,
    user_id: i32,
    rule_id: i32,
    baseline_at: DateTime<Utc>,
) -> Result<Vec<Attempt>, WisecrowError> {
    let rows: Vec<(Uuid, Uuid, bool, bool, DateTime<Utc>)> = sqlx::query_as(
        "SELECT event_id, session_id, correct, hint_shown, occurred_at
         FROM grammar_attempts
         WHERE user_id = $1 AND rule_id = $2 AND occurred_at >= $3
         ORDER BY occurred_at, event_id",
    )
    .bind(user_id)
    .bind(rule_id)
    .bind(baseline_at)
    .fetch_all(&mut **transaction)
    .await?;

    Ok(rows
        .into_iter()
        .map(
            |(event_id, session_id, correct, hint_shown, occurred_at)| Attempt {
                event_id,
                session_id,
                rule_id,
                correct,
                hint_shown,
                occurred_at,
            },
        )
        .collect())
}

async fn persist_projection(
    transaction: &mut Transaction<'_, Postgres>,
    user_id: i32,
    rule_id: i32,
    projection: &Projection,
    attempts: i32,
) -> Result<(), WisecrowError> {
    let card = projection.card;
    let accuracy = (attempts > 0).then_some(projection.accuracy);

    sqlx::query(
        "INSERT INTO grammar_mastery (
             user_id, rule_id, stability, difficulty, elapsed_days, scheduled_days,
             reps, lapses, state, accuracy, attempts, last_review, due
         ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
         ON CONFLICT (user_id, rule_id) DO UPDATE
         SET stability = EXCLUDED.stability, difficulty = EXCLUDED.difficulty,
             elapsed_days = EXCLUDED.elapsed_days, scheduled_days = EXCLUDED.scheduled_days,
             reps = EXCLUDED.reps, lapses = EXCLUDED.lapses, state = EXCLUDED.state,
             accuracy = EXCLUDED.accuracy, attempts = EXCLUDED.attempts,
             last_review = EXCLUDED.last_review, due = EXCLUDED.due",
    )
    .bind(user_id)
    .bind(rule_id)
    .bind(card.stability)
    .bind(card.difficulty)
    .bind(i32::try_from(card.elapsed_days).map_err(|_| day_overflow("elapsed"))?)
    .bind(i32::try_from(card.scheduled_days).map_err(|_| day_overflow("scheduled"))?)
    .bind(card.reps)
    .bind(card.lapses)
    .bind(CardStatus::from(card.status).to_db())
    .bind(accuracy)
    .bind(attempts)
    .bind(card.last_review)
    .bind(card.due)
    .execute(&mut **transaction)
    .await?;
    Ok(())
}

fn day_overflow(field: &str) -> WisecrowError {
    WisecrowError::InvalidInput(format!("FSRS {field} days exceed database bounds"))
}
