//! The shared grading contract.
//!
//! Correctness and hint usage feed both mastery projections, so neither client
//! may decide them for itself. Grading lived in a web component that compared
//! with `eq_ignore_ascii_case`, which holds `ÉTÉ` and `été` to be different
//! words, reported a bare boolean, and discarded whether a hint had been
//! revealed. A single pure grader here gives the web application, the mobile
//! application and the server one answer, and the server regrades every
//! submission it receives rather than trusting a client's verdict.

use unicode_normalization::UnicodeNormalization;
use uuid::Uuid;

/// An item reduced to what grading needs, stripped of presentation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GradableItem {
    Cloze {
        answer: String,
        accepted: Vec<String>,
    },
    MultipleChoice {
        options: Vec<(String, String)>,
        correct_option: String,
    },
}

impl GradableItem {
    /// Builds a cloze whose `accepted` forms are also correct.
    #[must_use]
    pub fn cloze(answer: &str, accepted: &[&str]) -> Self {
        Self::Cloze {
            answer: answer.to_owned(),
            accepted: accepted.iter().map(|form| (*form).to_owned()).collect(),
        }
    }

    /// Builds a multiple choice from `(identifier, text)` pairs.
    #[must_use]
    pub fn multiple_choice(options: &[(&str, &str)], correct_option: &str) -> Self {
        Self::MultipleChoice {
            options: options
                .iter()
                .map(|(id, text)| ((*id).to_owned(), (*text).to_owned()))
                .collect(),
            correct_option: correct_option.to_owned(),
        }
    }
}

/// What the learner offered.
///
/// A multiple choice carries the option's stable identifier rather than its
/// position, so that shuffling options for display cannot corrupt a result.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Answer {
    Text(String),
    Option(String),
}

/// One submission against one item revision.
///
/// The ordinal counts submissions within an interaction, so that the first
/// answer can be told from a retry; `event_id` is generated by the client so
/// that a submission replayed after an offline spell is recorded once.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Submission {
    pub item_id: i32,
    pub revision: i32,
    pub session_id: Uuid,
    pub event_id: Uuid,
    pub answer: Answer,
    pub hint_shown: bool,
    pub ordinal: u32,
}

impl Submission {
    /// A typed answer, unattributed to an item or session.
    ///
    /// Callers that know the item fill the remaining fields, which is why they
    /// are public; grading itself reads only `answer`.
    #[must_use]
    pub fn text(answer: &str) -> Self {
        Self::new(Answer::Text(answer.to_owned()))
    }

    /// A chosen option, unattributed to an item or session.
    #[must_use]
    pub fn option(option_id: &str) -> Self {
        Self::new(Answer::Option(option_id.to_owned()))
    }

    fn new(answer: Answer) -> Self {
        Self {
            item_id: 0,
            revision: 0,
            session_id: Uuid::nil(),
            event_id: Uuid::nil(),
            answer,
            hint_shown: false,
            ordinal: 1,
        }
    }
}

/// The grader's ruling on one submission.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Verdict {
    pub correct: bool,
}

/// Grades a submission against the item it was made on.
///
/// A submission whose shape does not match the item — a typed answer to a
/// multiple choice, say — is incorrect rather than an error, because no
/// sensible verdict exists and a client bug must not stall a session.
#[must_use]
pub fn grade(item: &GradableItem, submission: &Submission) -> Verdict {
    let correct = match (item, &submission.answer) {
        (GradableItem::Cloze { answer, accepted }, Answer::Text(given)) => {
            let given = normalise(given);
            std::iter::once(answer)
                .chain(accepted)
                .any(|form| normalise(form) == given)
        }
        (
            GradableItem::MultipleChoice {
                options,
                correct_option,
            },
            Answer::Option(chosen),
        ) => {
            // An item whose correct option is absent from its options is
            // broken; award nothing rather than accept an identifier that
            // names no choice the learner was offered.
            chosen == correct_option && options.iter().any(|(id, _)| id == correct_option)
        }
        _ => false,
    };
    Verdict { correct }
}

/// Folds a typed answer to the form comparison happens in.
///
/// Composition comes first so that a precomposed `é` and a decomposed `e` plus
/// combining acute agree; case folding is the full Unicode one, and runs of
/// whitespace collapse so that spacing never decides a verdict. Accents
/// themselves are preserved: `lete` is not `été`.
fn normalise(text: &str) -> String {
    let composed: String = text.nfc().collect();
    composed
        .to_lowercase()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;
    use rand::rngs::StdRng;
    use rand::seq::SliceRandom;
    use rand::SeedableRng;
    use rstest::rstest;

    #[rstest]
    #[case("été", "ÉTÉ", true)]
    #[case("  l'été ", "l'été", true)]
    #[case("lete", "été", false)]
    #[case("estoy", "estás", false)]
    fn cloze_grading_folds_unicode_case_and_trims(
        #[case] submitted: &str,
        #[case] answer: &str,
        #[case] expected: bool,
    ) {
        let item = GradableItem::cloze(answer, &[]);
        assert_eq!(grade(&item, &Submission::text(submitted)).correct, expected);
    }

    #[test]
    fn decomposed_and_precomposed_accents_agree() {
        let item = GradableItem::cloze("été", &[]);
        assert!(grade(&item, &Submission::text("e\u{301}te\u{301}")).correct);
    }

    #[test]
    fn interior_whitespace_collapses() {
        let item = GradableItem::cloze("ne sais pas", &[]);
        assert!(grade(&item, &Submission::text("ne   sais\tpas")).correct);
    }

    #[test]
    fn accepted_alternatives_are_honoured() {
        let item = GradableItem::cloze("ne sais pas", &["sais pas"]);
        assert!(grade(&item, &Submission::text("sais pas")).correct);
    }

    #[test]
    fn multiple_choice_resolves_by_option_id_not_index() {
        let item =
            GradableItem::multiple_choice(&[("o1", "ser"), ("o2", "estar"), ("o3", "haber")], "o2");
        assert!(grade(&item, &Submission::option("o2")).correct);
        assert!(!grade(&item, &Submission::option("o1")).correct);
    }

    #[test]
    fn an_option_naming_no_choice_is_never_correct() {
        let item = GradableItem::multiple_choice(&[("o1", "ser"), ("o2", "estar")], "o9");
        assert!(!grade(&item, &Submission::option("o9")).correct);
    }

    #[test]
    fn a_submission_of_the_wrong_shape_is_incorrect() {
        let item =
            GradableItem::multiple_choice(&[("o1", "ser"), ("o2", "estar"), ("o3", "haber")], "o2");
        assert!(!grade(&item, &Submission::text("estar")).correct);
    }

    proptest! {
        #[test]
        fn grading_is_stable_under_option_shuffling(seed in 0u64..1000) {
            let mut options = vec![
                ("o1", "ser"),
                ("o2", "estar"),
                ("o3", "haber"),
                ("o4", "tener"),
            ];
            options.shuffle(&mut StdRng::seed_from_u64(seed));

            let item = GradableItem::multiple_choice(&options, "o2");
            prop_assert!(grade(&item, &Submission::option("o2")).correct);
            prop_assert!(!grade(&item, &Submission::option("o3")).correct);
        }
    }
}
