[v1]
"cargo-audit 0.20.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-expand 1.0.88 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-modules 0.16.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-modules"]
"cargo-nextest 0.9.72 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"cargo-watch 8.5.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
