[v1]
"cargo-audit 0.20.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-expand 1.0.91 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-modules 0.17.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-modules"]
"cargo-nextest 0.9.81 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"cargo-watch 8.5.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
